import { defineNuxtModule, createResolver, addServerImportsDir, addTypeTemplate } from '@nuxt/kit';
import { defu } from 'defu';
import type { ModuleOptions } from './types';

export type { ModuleOptions };

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: '@fatturazione-elettronica-aruba/nuxt',
    configKey: 'fatturazioneAruba',
    compatibility: {
      nuxt: '>=3.0.0',
    },
  },
  defaults: {
    environment: 'demo',
  },
  setup(options, nuxt) {
    const { resolve } = createResolver(import.meta.url);

    // Validate required options
    if (!options.username) {
      console.warn(
        '[@fatturazione-elettronica-aruba/nuxt] Missing `username` in module options or NUXT_FATTURAZIONE_ARUBA_USERNAME env variable'
      );
    }
    if (!options.password) {
      console.warn(
        '[@fatturazione-elettronica-aruba/nuxt] Missing `password` in module options or NUXT_FATTURAZIONE_ARUBA_PASSWORD env variable'
      );
    }

    // Extend runtime config (server-only for security)
    nuxt.options.runtimeConfig.fatturazioneAruba = defu(
      nuxt.options.runtimeConfig.fatturazioneAruba || {},
      {
        username: options.username || '',
        password: options.password || '',
        environment: options.environment || 'demo',
      }
    );

    // Add server-only utilities (composables)
    addServerImportsDir(resolve('./runtime/server/utils'));

    // Add type declarations
    addTypeTemplate({
      filename: 'types/fatturazione-elettronica-aruba.d.ts',
      getContents: () => `
// Generated by @fatturazione-elettronica-aruba/nuxt
import type { ArubaClient } from '@fatturazione-elettronica-aruba/core';
import type { InvoicesClient } from '@fatturazione-elettronica-aruba/invoices';
import type { NotificationsClient } from '@fatturazione-elettronica-aruba/notifications';
import type { CommunicationsClient } from '@fatturazione-elettronica-aruba/communications';

declare module 'nitropack' {
  interface NitroRuntimeConfig {
    fatturazioneAruba: {
      username: string;
      password: string;
      environment: 'demo' | 'production';
    };
  }
}

declare module '#imports' {
  export function useArubaClient(): ArubaClient;
  export function useArubaInvoices(): InvoicesClient;
  export function useArubaNotifications(): NotificationsClient;
  export function useArubaCommunications(): CommunicationsClient;
}

export {};
`,
    });

    // Log successful setup
    console.log(
      `[@fatturazione-elettronica-aruba/nuxt] Module loaded (environment: ${options.environment})`
    );
  },
});
